### ISSUE TITLE
你好，请问eplot是否还尚未适配pyecharts 1.x

### ISSUE THREAD

**Issue by veink-y** [pjgao/eplot#1]

**Comment by pjgao** [comment]
是的，pyecharts 1.x好像改了些接口，我有时间马上修改eplot

**Comment by danielwu37** [comment]
期待对最新的1.2版本的支持

**Comment by sunxiaolong321** [comment]
期待

**Comment by danielwu37** [comment]
未

发自我的 iPhone

**Comment by Max-PJB** [comment]
pyecharts 已经1.6 了，大佬，跪求更新啊

**Comment by pjgao** [comment]
> pyecharts 已经1.6 了，大佬，跪求更新啊

之前对1.5版本的部分功能更新了，1.6版本的又不行了吗？我个人最近不怎么用到Pyecharts，所以更新的不太及时。
